name: Run Ahrefs Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write credentials.json
        run: echo "${{ secrets.GOOGLE_JSON }}" > credentials.json

      - name: Run scraper
        run: python ahrefs_scraper.py
