name: Run Ahrefs Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write credentials.json
        shell: bash
        run: |
          printf "%s" "$GOOGLE_JSON" > credentials.json
        env:
          GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}

      - name: Run scraper
        run: python ahrefs_scraper.py
