name: Scrape Referring URLs

on:
  schedule:
    - cron: "0 * * * *"  # every 1 hour
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install chromium

    - name: Run script
      env:
        GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
      run: |
        python main.py
